[build]
  command = "yarn install --immutable && yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22"

[[headers]]
  for = "/_app/immutable/*"
  [headers.values]
    cache-control = "public, immutable, max-age=31536000"